### ISSUE TITLE
[feature request] Civil Twilight - 6 degrees 

### ISSUE THREAD

**Issue by marius-sucan** [signetica/SunRise#4]
Hello!

Is it possible for this library to also calculate the Civil Twilight?

According to Wikipedia, civil twlight is when the sun is between 6 and 0 degrees below the horizon line. The library could just report the time when the sun is at 6 degrees, eg. sr.riseCivilTwilightTime and sr.setCivilTwilightTime.

Thank you.  If my request entails a lot of work, please let me know and I will be happy to just display the sunset and sunrise in my application. Otherwise , if it is not too much work and you see this fit to add, I would be thankful.

Best regards, Marius.

**Comment by signetica** [comment]
Hi Marius,

While it is certainly possible to modify the technique used in SunRise to calculate twilight, it is not the easiest or best way to accomplish this.

The duration of twilight, that is, the time from sunset to twilight, is a much simpler problem.

The Wikipedia page for twilight has a link to a simple formula:
https://web.archive.org/web/20130122033117/http://www.gandraxa.com/length_of_day.xml

I do not doubt that you can find pre-existing code to do this - but if not, send me a note and I'll write it.  However, I would prefer not to duplicate existing work.

Also, let me know what you pick, as I am interested.

Best wishes,
Cyrus

**Comment by marius-sucan** [comment]
Hello! 

Thank you for the quick response. 

I found this:
https://stackoverflow.com/questions/2609536/how-to-calculate-dawn-dusk-times

http://souptonuts.sourceforge.net/code/sunrise.c.html

It is suggested that one just has to change the angle, from 90 to 96.

I'm currently winding down, on the phone. I'll try this code tomorrow and also try changing the angle. I hope it'll give the correct results. 

I'll get back to you with the results. If it's a good code or not.

Best regards, Marius.

**Comment by marius-sucan** [comment]
As promised, I am back.

The code I found is... quite interesting.

It has two functions: calcHourAngleSunrise() and calcHourAngleSunset(), both use the constant 90.833°. However , this angle seems to be incorrect. I have to manually fine-tune the values to get the correct results for sunset and sunrise for a given location. The angles are dependent on lat/long. So, it is not reliably usable for any scenario, nor Civil Twilight.

I also found this:
https://stackoverflow.com/questions/2056555/c-sharp-sunrise-sunset-with-latitude-longitude

Tons of links to go through there, to sort through rubble. I went through a few, found some implementations that looked very similar to the one I already posted , using the same value: 90.833. 

I would appreciate if you would implement Civil Twilight in your class. I insist on this because it is the only code I found that gives correct results for sunset/sunrise times, for varying locations.

Best regards, Marius.

**Comment by signetica** [comment]
Marius,

The problem of calculating the sun's position at a given time is complicated but the solution is, at least with computers, an easily calculated formula.  But the formula's inverse is not easy, and so you can't take the altitude of the sun and write down a simple formula to calculate the time it will be there.

So you instead calculate the position of the sun at multiple times and iteratively get closer to the time you are interested in.

The problem of calculating the sunset is therefore one of finding this time in a computationally efficient way.

Your proposed software starts with a very simple formula for the sun's position and does a very simple single-iteration calculation of the sunset time.  So it is not very accurate.

The way I've done it is optimized to calculate sunrise/sunset more accurately than this.  Adding dusk calculations to it is not impossible, but it involves making the code more complex, which I would rather avoid because it will make the code harder to maintain and therefore less reliable.  This might be worth it but in general very accurate calculations of the start of civil twilight are not important.

Greater accuracy than a couple of minutes is only useful in obscure legal areas.  Even in aviation, the difficulty of defining the exact second of the end of twilight is circumvented by using the definition of '30 minutes after sunset'.

It's not as simple as just changing the angle from 0 to 6 degrees, since atmospheric refraction must be considered, and sunset isn't when the center of the sun crosses the horizon, but it's upper edge. And this is completely unnecessary, since the time from sunset to approximately 6 degrees below the horizon is a very simple geometry problem with an analytic formula to calculate it.

The simple way to solve your problem is to calculate how long it will take the sun to travel 6 degrees below the horizon on a particular day at a particular latitude and longitude, and add that to the sunset time.  It's a simple formula.  It will give you the correct answer within a minute or two - and this is pretty good for something as vague as the transition from civil to nautical twilight.

So take a look at the formula in the Wikipedia article's footnote.  If you have trouble with it let me know.

Cyrus

**Comment by marius-sucan** [comment]
Hello!

Thank you very much for the comprehensive reply. It was illuminating for me.  Yesterday I extensively tested your library and I was amazed of its accuracy. Now, I understand better why.

I will pay close attention to the article you pointed me and try to implement the formula. I will let you know if I succeed or not.

Best regards, Marius.

**Comment by marius-sucan** [comment]
Hello!

I implemented the formula in C++ to the best of my knowledge, but I think it does not yield the correct results. Being rather a novice myself in C++ I am not sure I implemented correctly the formula.

```
double degToRad(double angleDeg) {
   return (M_PI * angleDeg / 180.0);
}

double radToDeg(double angleRad) {
  return (180.0 * angleRad / M_PI);
}

void calcDayLength() {
  const double h = 6; // civil twilight angle
  const double j = M_PI/182.625;
  const double axis = 23.439;

  int day = 263;   // winter solstice was on 21st of December, day 355; today is the 273rd day of 2022, minus 10 days
  double lat = 46.186;
  double lon = 21.312; // ignored in the formulas


  double r = degToRad(j * day);
  double g = radToDeg(axis * cos(r));  // i suppose axis*cos(r) has to be converted to degrees for tan(); perhaps I am wrong


  double b = 1 - tan(lat) * tan(g);   // length of daylight
  double n = 1 - tan(lat) * tan(g) + h/cos(degToRad(lat));   // length of daylight and both twlights up to h;
  double e = (acos(1 - n)/180 - b) / 2;
  double p = acos(1 - b)/180;
  // deleted the printf() calls
}
```

Please let me know if the code is correct or not.

This is the output I get: `day=263
  r=0.078963
  g=1338.771199
  b=1.663087
  n=10.329606
  e=nan
  p=0.012754`

Thank you.

Best regards, Marius.

**Comment by signetica** [comment]
I'll take a look at it later, when I am not quite so busy.

**Comment by signetica** [comment]
I have invited you to look at a repository with an implementation of this method.  It's not quite finished but it should be fine for a test.  I'm closing this issue, we can talk about it there.
